sudo: required
language: java
jdk:
  - oraclejdk8

install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo apt update -y && sudo apt install ffmpeg  
  - sudo find / -name ffmpeg
  - mvn install -Dgpg.skip
script: mvn clean compile
