sudo: required
language: java
jdk:
  - oraclejdk8

install:
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-3
  - sudo apt update && sudo apt install ffmpeg libav-tools x264 x265
  - mvn install -Dgpg.skip
script: mvn clean compile
