sudo: required
services:
- docker
language: java
jdk:
- oraclejdk9
install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
- sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
- sudo apt-get update
- sudo apt-get install ffmpeg
- mvn clean package 
- mv $TRAVIS_BUILD_DIR/target/VideoTranscoding-Backend-BETA-0.5.jar VideoTranscoding-Backend-BETA-0.5.jar
- docker build -t luiscajl/videotranscoding:0.5 .
- docker push luiscajl/videotranscoding:0.5

