sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
  - sudo apt update -y && sudo apt install ffmpeg  
  - sudo find / -name ffmpeg
  - mvn install -Dgpg.skip
  - mvn clean compile
  - docker --version
# - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_USERNAMEvideotranscoding:0.2 .
  - docker push $DOCKER_USERNAME/videotranscoding:0.2

