sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD ;
- mvn clean package -Dmaven.test.skip=true
- mv $TRAVIS_BUILD_DIR/target/VideoTranscoding--BETA-0.2.jar VideoTranscoding--BETA-0.2.jar
- docker build -t luiscajl/videotranscoding .
- docker push luiscajl/videotranscoding:latest
env:
  matrix:
  - secure: YLbecnxoEmgPS/nT1axNj6GriAzu0MBrbctXTuPJPfGIAaOmYwIy0VAnBRwaTeTxPmoZRpgaO6WYSozXWEEvP+X5Yo4BcsnuF/hkfcgZYl67OVviFN2gJm3p7XeJry07i2DJjFVfwtK0q06ZFIp06z7OVd3s6DmlaMtI7o6Wj12bnnLuNdTGfmtKZFKkMW8GnxY5EAoYyy0t/8tu4azMMZFq3M6ssHA+horsmqOMyztD6jz5lCxaNE6Ui948K7wzk0vZ8LKUk4Ht4ltFY75d3otnJK4LB8GAwBNQNmg4hB/Wxn0oZCHzC5rdesc1Yo0gu3VPONvLyIjHQi3vOJsAZzsZeiw6qr4y/Zaee5ii0v09V6UNwVf6aQ9Fn1Sej8baehuAjPr6BfwtnJ1vEThq1nLp5rzCNxU54Fn0m6ctdmIlk1NKIonopqDbj1CCOg/20zoppg8Arf4mgM1BKflsQhFwKq3N3MSk9O8SLOC9S/0g7Ti+J1pjnnwBtDF57LlrnynlznNBxOAlzLQojFMDFenrrEd6rKfMkY1XDzTbkkKedjy7HrO2REI6PZiJZmvSZyn12tmOD9U0l/7tOBo0F/+uRgQDuEbzgxzZoi4ol61GbB4S1cbRqZbMO3S6LAR9ezw4oHhhP9g6QQxmSqVsJxSQApHmKA/lKtHrq75Bosg=
  - secure: nxNYHXkCgouOoG5F4GsMC9kHDrbAaiS/ptqGGwDC38yTyqasrv2QP5ZqVyypNebrMEglHSrdGrzk8Vr7CSEs0joMDe8lBuUPUKklgpGEMReIxbAm5fJyFZw+fscrWkFwnLG/Gbb8SovAnzO/UPlMIGux2JPkeKvR13hL6nK+wS7v35bYl2XZ2Mf26ZHgsYpY10rBrrOU9qSYs7fSdINk72R42ERmGQ+maiGvZdQr/+I720O3WZz8r+pxW+6Y/dQ6ZvmwNaKEPZ3X9OKK41yRoJwnSREErtOTypH0vqQhlxZUkgXhmWLxAZ4v3XP8chPwv5jeyqIXRLtwZK4udVAT510Egd8LwoWyMjD2SEtTKG2YcDsD6TKJ7runo39sAj78zcfV1lZA23zMyxxQDtz/5Q7yzPbydqpvhmdmXZoQOiWEuCroWEIiDAoOhzve4n1fk0VFNVTPxs20eus1MRs0cl/pHiJ3au+SoRar2fIWO7E/UVPA8kjIKjPDe7runSnJxLj51EC1i0xgFBWnwIjqQraQsr5PdP/q00M20XrbOuYNwhCKKQ6pYGcyWL0011xZLzyB4tO0BqxFafqD8z1wZApLV2SI4a+rZUw927KOkPOzRZdeQnLj3VCDvKcb6irrPNbeuSZA8Ivk3ce0+axb/CDaB/afWiMzYBiC9unAig8=
