sudo: required
addons:
  ssh_known_hosts:
  - lavandadelpatio.es
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
- mvn clean package 
- mv $TRAVIS_BUILD_DIR/target/VideoTranscoding--BETA-0.2.jar VideoTranscoding--BETA-0.2.jar
- docker build -t luiscajl/videotranscoding .
- docker push luiscajl/videotranscoding:latest
- sudo apt-get install sshpass
- chmod +x ./scripts/docker_deploy.sh
deploy:
 provider: script
 skip_cleanup: true
 script: sh ./scripts/docker_deploy.sh

