sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 
- sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
- sudo apt update -y && sudo apt install ffmpeg 
- mvn clean package 
- mv $TRAVIS_BUILD_DIR/target/VideoTranscoding--BETA-0.2.jar VideoTranscoding--BETA-0.2.jar
- docker build -t luiscajl/videotranscoding .
- docker push luiscajl/videotranscoding:latest

