sudo: required
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7
language: java
jdk:
  - oraclejdk8
before_install:
 - ./scripts/install_ffmpeg_centos7.sh
install: mvn install -Dgpg.skip
script: mvn clean compile
