version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: videotranscoding-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lavanda
      - MYSQL_DATABASE=videotranscoding
  spring-backend:
    depends_on:
      - mysql
    image: luiscajl/videotranscoding:latest
    container_name: videotranscoding-backend
    ports:
      - 8443:8443
    links:
      - mysql:mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/videotranscoding
      - JVM_OPTS=-Xmx4g -Xms4g -XX:MaxPermSize=1024m
