version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-spring
    environment:
      - MYSQL_ROOT_PASSWORD=lavanda
      - MYSQL_DATABASE=videotranscoding
 
  spring-repository:
    depends_on:
      - mysql
    image: luiscajl/videotranscoding:latest
    container_name: springbackend
    ports:
      - 8080:8080
    links:
      - mysql:mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/videotranscoding
